import React,{useState}from'react';
import{SafeAreaView,View,Text,StyleSheet,Pressable,Image,ScrollView,ActivityIndicator,Alert}from'react-native';
import*as ImagePicker from'expo-image-picker';
import{LinearGradient}from'expo-linear-gradient';
import{UseitApiProvider,analyzeForConsumer}from'../src/core/intelligence/apiClient';
import type{OpportunityKind}from'../src/core/intelligence/types';
import type{PresentationResult}from'../src/core/intelligence/presentation';

const API_URL=process.env.EXPO_PUBLIC_USEIT_API_URL||'';
const modes:[OpportunityKind,string][]=[['create','Turn what you have into something new.'],['improve','Make your space or things better.'],['fix','Figure out what to do next.'],['cook','Make something from what you have.'],['surprise','Show me something I would not think of.']];

export default function Home(){
 const[photo,setPhoto]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[result,setResult]=useState<PresentationResult|null>(null);
 async function analyze(intent?:OpportunityKind){
  if(!API_URL){Alert.alert('USEIT is not connected','Set EXPO_PUBLIC_USEIT_API_URL before running the real vision flow.');return}
  if(!photo)return;setBusy(true);
  try{const provider=new UseitApiProvider(API_URL);setResult(await analyzeForConsumer(provider,photo,intent))}catch(e){Alert.alert('Could not understand the image','Please try again with a clearer photo.')}finally{setBusy(false)}
 }
 async function capture(){const r=await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.85,base64:true});if(r.canceled)return;const a=r.assets[0];if(!a.base64){Alert.alert('Photo unavailable','USEIT could not read the captured image.');return}setPhoto(`data:${a.mimeType||'image/jpeg'};base64,${a.base64}`);setResult(null)}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
 {!photo?<><Text style={s.logo}>USEIT</Text><Text style={s.kicker}>SEE WHAT’S POSSIBLE</Text><Text style={s.hero}>Show me what{`\n`}you have.</Text><Text style={s.sub}>Point your camera at almost anything. USEIT helps you discover what you can do with it.</Text><Pressable onPress={capture} style={s.capture}><LinearGradient colors={['#111','#3b3b3b']} style={s.grad}><Text style={s.cam}>⌾</Text><Text style={s.cta}>SHOW ME</Text><Text style={s.hint}>Take a photo</Text></LinearGradient></Pressable><View style={s.tags}>{['ROOMS','OBJECTS','FOOD','MATERIALS'].map(x=><Text style={s.tag} key={x}>{x}</Text>)}</View></>:
 <><View style={s.top}><Text style={s.small}>USEIT</Text><Pressable onPress={()=>{setPhoto(null);setResult(null)}}><Text style={s.close}>✕</Text></Pressable></View><Image source={{uri:photo}} style={s.photo}/>{busy?<View style={s.loading}><ActivityIndicator size="large"/><Text style={s.load}>Understanding what I see…</Text></View>:result?<><Text style={s.kicker}>ONE IDEA</Text><Text style={s.title}>{result.hero?.title||'Here is what I found'}</Text><Text style={s.sub}>{result.hero?.description||'I found several possibilities in your scene.'}</Text>{result.hero?.durationMinutes?<Text style={s.meta}>{result.hero.durationMinutes} MIN · {result.hero.effort.toUpperCase()}</Text>:null}<Pressable style={s.primary} onPress={()=>Alert.alert('Next step','Guided execution is being built into USEIT.') }><Text style={s.primaryText}>SHOW ME HOW</Text></Pressable>{result.alternatives.map(x=><View style={s.alt} key={x.id}><Text style={s.altTitle}>{x.title}</Text><Text style={s.altDesc}>{x.description}</Text></View>)}<Pressable style={s.secondary} onPress={()=>{setPhoto(null);setResult(null)}}><Text>TRY ANOTHER PHOTO</Text></Pressable></>:<><Text style={s.title}>What should I do with this?</Text>{modes.map(([a,b])=><Pressable key={a} style={s.mode} onPress={()=>analyze(a)}><Text style={s.modeTitle}>{a.toUpperCase()}</Text><Text style={s.modeDesc}>{b}</Text><Text style={s.arrow}>›</Text></Pressable>)}</>}</>}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F7F2'},page:{padding:24,paddingTop:28,paddingBottom:60},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},logo:{fontSize:36,fontWeight:'900',letterSpacing:-2,color:'#111',marginTop:12},small:{fontSize:18,fontWeight:'900',letterSpacing:-1},close:{fontSize:20,color:'#777'},kicker:{fontSize:11,fontWeight:'800',letterSpacing:2,color:'#777',marginTop:58},hero:{fontSize:52,lineHeight:53,fontWeight:'800',letterSpacing:-2.5,color:'#111',marginTop:10},title:{fontSize:42,lineHeight:44,fontWeight:'800',letterSpacing:-2,color:'#111',marginVertical:20},sub:{fontSize:17,lineHeight:25,color:'#666',marginTop:16},capture:{marginTop:36,borderRadius:28,overflow:'hidden'},grad:{padding:30,alignItems:'center'},cam:{fontSize:30,color:'#fff'},cta:{fontSize:20,fontWeight:'900',letterSpacing:1,color:'#fff',marginTop:8},hint:{fontSize:12,color:'#aaa',marginTop:6},tags:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:26},tag:{borderWidth:1,borderColor:'#ddd',borderRadius:20,paddingHorizontal:12,paddingVertical:7,fontSize:10,fontWeight:'800',color:'#777'},photo:{width:'100%',height:320,borderRadius:26},loading:{alignItems:'center',paddingTop:55},load:{marginTop:14,color:'#666'},mode:{backgroundColor:'#fff',borderRadius:20,padding:20,marginBottom:10,borderWidth:1,borderColor:'#e5e5df'},modeTitle:{fontSize:20,fontWeight:'900'},modeDesc:{fontSize:14,color:'#777',marginTop:4,maxWidth:'85%'},arrow:{position:'absolute',right:18,top:17,fontSize:28,color:'#aaa'},meta:{fontSize:11,fontWeight:'900',letterSpacing:1,color:'#999',marginTop:20},primary:{backgroundColor:'#111',padding:18,borderRadius:18,alignItems:'center',marginTop:28},primaryText:{color:'#fff',fontWeight:'900'},secondary:{padding:18,alignItems:'center',marginTop:8},alt:{backgroundColor:'#fff',borderRadius:18,padding:18,marginTop:10},altTitle:{fontSize:18,fontWeight:'800'},altDesc:{fontSize:14,color:'#666',marginTop:5}});