/**
 * Report Exporter
 * Generates text and PDF reports from diagnostic data
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { DiagnosticReport, DiagnosticStatus } from '../adb/DiagnosticCommands';

const STATUS_ICONS: Record<DiagnosticStatus, string> = {
  ok: '[OK]',
  warning: '[WARN]',
  fault: '[FAULT]',
  unknown: '[UNKN]',
  running: '[...]',
};

const STATUS_ICONS_HTML: Record<DiagnosticStatus, string> = {
  ok: '<span style="color:#22c55e">✓</span>',
  warning: '<span style="color:#f59e0b">⚠</span>',
  fault: '<span style="color:#ef4444">✗</span>',
  unknown: '<span style="color:#7F8EA3">?</span>',
  running: '<span style="color:#3b82f6">►</span>',
};

export function generateTextReport(
  report: DiagnosticReport,
  lang: 'en' | 'hu' = 'en'
): string {
  const lines: string[] = [];

  lines.push('=' .repeat(60));
  lines.push('POS DOCTOR - DIAGNOSTIC REPORT');
  lines.push('=' .repeat(60));
  lines.push(`Date/Time : ${new Date(report.timestamp).toLocaleString()}`);
  lines.push(`Device    : ${report.deviceManufacturer} ${report.deviceModel}`);
  lines.push(`Serial    : ${report.deviceSerial}`);
  lines.push(`IP        : ${report.deviceIp}`);
  lines.push(`Android   : ${report.androidVersion}`);
  lines.push(`Health    : ${report.overallScore}% (${report.overallStatus.toUpperCase()})`);
  lines.push('-' .repeat(60));
  lines.push('');

  for (const cat of report.categories) {
    const title = lang === 'hu' ? cat.title.hu : cat.title.en;
    const icon = STATUS_ICONS[cat.status];
    const summary = lang === 'hu' ? cat.summary.hu : cat.summary.en;
    lines.push(`${icon} ${title}`);
    lines.push(`    Summary: ${summary}`);

    for (const field of cat.fields) {
      const fieldStatus = field.status ? STATUS_ICONS[field.status] + ' ' : '';
      lines.push(`    ${fieldStatus}${field.key}: ${field.value}`);
    }

    lines.push('--- Raw Output ---');
    const raw = cat.rawOutput.slice(0, 800);
    raw.split('\n').slice(0, 20).forEach((l) => lines.push('  ' + l));
    lines.push('');
  }

  lines.push('=' .repeat(60));
  lines.push('Generated by POS Doctor');
  lines.push('=' .repeat(60));

  return lines.join('\n');
}

export function generateHtmlReport(
  report: DiagnosticReport,
  lang: 'en' | 'hu' = 'en'
): string {
  const statusColor: Record<string, string> = {
    ok: '#22c55e', warning: '#f59e0b', fault: '#ef4444', unknown: '#7F8EA3',
  };

  const categoryRows = report.categories.map((cat) => {
    const title = lang === 'hu' ? cat.title.hu : cat.title.en;
    const summary = lang === 'hu' ? cat.summary.hu : cat.summary.en;
    const icon = STATUS_ICONS_HTML[cat.status];
    const color = statusColor[cat.status] || '#7F8EA3';

    const fieldRows = cat.fields.map((f) => {
      const fc = f.status ? statusColor[f.status] || '#EAF0F7' : '#EAF0F7';
      return `<tr>
        <td style="color:#B7C3D4;padding:3px 8px;font-size:12px">${f.key}</td>
        <td style="color:${fc};padding:3px 8px;font-size:12px">${f.value}</td>
      </tr>`;
    }).join('');

    return `
      <div style="background:#121823;border:1px solid #243042;border-radius:12px;margin-bottom:12px;padding:14px">
        <div style="display:flex;align-items:center;margin-bottom:8px">
          <span style="font-size:18px;margin-right:8px">${icon}</span>
          <span style="font-size:15px;font-weight:700;color:#EAF0F7">${title}</span>
          <span style="margin-left:auto;font-size:12px;font-weight:600;color:${color};background:${color}22;padding:2px 10px;border-radius:999px">${cat.status.toUpperCase()}</span>
        </div>
        <p style="color:#B7C3D4;font-size:13px;margin:4px 0 10px">${summary}</p>
        <table style="width:100%;border-collapse:collapse">${fieldRows}</table>
        <details style="margin-top:10px">
          <summary style="color:#7F8EA3;font-size:12px;cursor:pointer">Raw Output</summary>
          <pre style="background:#0F1520;color:#B7C3D4;font-size:11px;padding:8px;border-radius:8px;overflow-x:auto;white-space:pre-wrap;margin-top:6px">${escHtml(cat.rawOutput.slice(0, 1000))}</pre>
        </details>
      </div>`;
  }).join('');

  const scoreColor = report.overallScore >= 80 ? '#22c55e' : report.overallScore >= 60 ? '#f59e0b' : '#ef4444';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>POS Doctor Report - ${report.deviceModel}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #0B0D10; color: #EAF0F7; font-family: -apple-system, Roboto, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
  </style>
</head>
<body>
  <div style="background:#10141A;border-radius:16px;padding:20px;margin-bottom:20px;border:1px solid #243042">
    <h1 style="font-size:24px;margin-bottom:4px">POS Doctor</h1>
    <p style="color:#B7C3D4;font-size:13px">Diagnostic Report</p>
    <div style="margin-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:8px">
      <div><span style="color:#7F8EA3;font-size:12px">Device</span><br><span style="font-weight:600">${report.deviceManufacturer} ${report.deviceModel}</span></div>
      <div><span style="color:#7F8EA3;font-size:12px">Serial</span><br><span style="font-family:monospace">${report.deviceSerial}</span></div>
      <div><span style="color:#7F8EA3;font-size:12px">IP Address</span><br><span style="font-family:monospace">${report.deviceIp}</span></div>
      <div><span style="color:#7F8EA3;font-size:12px">Android</span><br><span>${report.androidVersion}</span></div>
      <div><span style="color:#7F8EA3;font-size:12px">Date/Time</span><br><span style="font-size:13px">${new Date(report.timestamp).toLocaleString()}</span></div>
      <div><span style="color:#7F8EA3;font-size:12px">Overall Health</span><br><span style="font-size:24px;font-weight:700;color:${scoreColor}">${report.overallScore}%</span></div>
    </div>
  </div>
  ${categoryRows}
  <p style="text-align:center;color:#7F8EA3;font-size:12px;margin-top:20px">Generated by POS Doctor</p>
</body>
</html>`;
}

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export async function exportAsPdf(
  report: DiagnosticReport,
  lang: 'en' | 'hu' = 'en'
): Promise<string> {
  const html = generateHtmlReport(report, lang);
  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });
  return uri;
}

export async function shareReport(
  report: DiagnosticReport,
  lang: 'en' | 'hu' = 'en',
  format: 'text' | 'pdf' = 'pdf'
): Promise<void> {
  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error('Sharing not available on this device');
  }

  if (format === 'pdf') {
    const pdfUri = await exportAsPdf(report, lang);
    await Sharing.shareAsync(pdfUri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share Diagnostic Report',
    });
  } else {
    const text = generateTextReport(report, lang);
    // Write text to temp file
    const { FileSystem } = require('expo-file-system');
    const path = `${FileSystem.cacheDirectory}pos_doctor_report_${Date.now()}.txt`;
    await FileSystem.writeAsStringAsync(path, text);
    await Sharing.shareAsync(path, {
      mimeType: 'text/plain',
      dialogTitle: 'Share Diagnostic Report',
    });
  }
}
