apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.posdoctordiagnostics'
version = '1.0.0'

android {
  compileSdkVersion 34

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 34
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
  }

  kotlinOptions {
    jvmTarget = '11'
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${getKotlinVersion()}"
}
